### ISSUE TITLE
Can't build tests on Ubuntu 22.04 (Jammy)

### ISSUE THREAD

**Issue by umanwizard** [mfontanini/cppkafka#294]
Due to this issue: https://github.com/catchorg/Catch2/issues/2178

```
In file included from /usr/include/signal.h:328,
                 from /home/brennan/code/cppkafka/third_party/Catch2/single_include/catch.hpp:4811,
                 from /home/brennan/code/cppkafka/tests/test_main.cpp:3:
/home/brennan/code/cppkafka/third_party/Catch2/single_include/catch.hpp:7441:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 7441 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
      |                                             ^~~~~~~~
make[2]: *** [tests/CMakeFiles/cppkafka_tests.dir/build.make:216: tests/CMakeFiles/cppkafka_tests.dir/test_main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:452: tests/CMakeFiles/cppkafka_tests.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by jlcordeiro** [comment]
From glibc ≥ ~2.34 SIGSTKSZ is no longer constexpr

Relatively easy to repro if you build on docker. Builds on ubuntu 20.04 for example will work fine. Builds on 24.04 have the issue

`FROM ubuntu:24.04
`

Currently I'm using a quick hack to get things building just by setting on build:

` -DCMAKE_CXX_FLAGS='-DCATCH_CONFIG_NO_POSIX_SIGNALS -DSIGSTKSZ=0' 
`

**Comment by jlcordeiro** [comment]
Sent PR with proposed fix:
https://github.com/mfontanini/cppkafka/pull/323
